/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SignitureBuilder {
        "fileUrl": string;
    }
}
declare global {
    interface HTMLSignitureBuilderElement extends Components.SignitureBuilder, HTMLStencilElement {
    }
    var HTMLSignitureBuilderElement: {
        prototype: HTMLSignitureBuilderElement;
        new (): HTMLSignitureBuilderElement;
    };
    interface HTMLElementTagNameMap {
        "signiture-builder": HTMLSignitureBuilderElement;
    }
}
declare namespace LocalJSX {
    interface SignitureBuilder {
        "fileUrl"?: string;
    }
    interface IntrinsicElements {
        "signiture-builder": SignitureBuilder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "signiture-builder": LocalJSX.SignitureBuilder & JSXBase.HTMLAttributes<HTMLSignitureBuilderElement>;
        }
    }
}
